(function () {
  'use strict';

  const supported = [
    { code: 'zh-CN', short: '中', native: '简体中文', name: 'Chinese', flag: '🇨🇳', dir: 'ltr', voice: 'zh-CN' },
    { code: 'en', short: 'EN', native: 'English', name: 'English', flag: '🇬🇧', dir: 'ltr', voice: 'en-US' },
    { code: 'ja', short: '日', native: '日本語', name: 'Japanese', flag: '🇯🇵', dir: 'ltr', voice: 'ja-JP' },
    { code: 'ko', short: '한', native: '한국어', name: 'Korean', flag: '🇰🇷', dir: 'ltr', voice: 'ko-KR' },
    { code: 'fr', short: 'FR', native: 'Français', name: 'French', flag: '🇫🇷', dir: 'ltr', voice: 'fr-FR' },
    { code: 'es', short: 'ES', native: 'Español', name: 'Spanish', flag: '🇪🇸', dir: 'ltr', voice: 'es-ES' },
    { code: 'de', short: 'DE', native: 'Deutsch', name: 'German', flag: '🇩🇪', dir: 'ltr', voice: 'de-DE' },
    { code: 'it', short: 'IT', native: 'Italiano', name: 'Italian', flag: '🇮🇹', dir: 'ltr', voice: 'it-IT' },
    { code: 'th', short: 'ไทย', native: 'ภาษาไทย', name: 'Thai', flag: '🇹🇭', dir: 'ltr', voice: 'th-TH' },
    { code: 'ar', short: 'ع', native: 'العربية', name: 'Arabic', flag: '🇸🇦', dir: 'rtl', voice: 'ar-SA' },
    { code: 'ru', short: 'RU', native: 'Русский', name: 'Russian', flag: '🇷🇺', dir: 'ltr', voice: 'ru-RU' },
    { code: 'pt-BR', short: 'PT', native: 'Português', name: 'Portuguese', flag: '🇧🇷', dir: 'ltr', voice: 'pt-BR' }
  ];

  const en = {
    demoRibbon: 'Demo · Bookings and live data are simulated', appName: 'EasyTrip', chooseLanguage: 'Choose language', scopeDomestic: 'Domestic trip', scopeInternational: 'International trip', weatherSuitable: 'Travel weather updated',
    heroEyebrow: 'One plan for domestic and global travel', heroTitle: 'Tell us your needs. Your trip is ready.', heroSubtitle: 'Fast for younger travelers, clear and independent for parents.',
    domestic: 'Domestic', international: 'International', promptLabel: 'How would you like to travel?', voiceInput: 'Describe by voice',
    confirmInfo: 'Confirm trip basics', optional: 'Optional', startDate: 'Departure date', tripDays: 'Trip length', travelers: 'Travelers', budget: 'Budget', pace: 'Travel pace', interests: 'Include', generate: 'Create complete trip plan',
    dailyPlan: 'Daily plan', bookingServices: 'Bookings', preparation: 'Trip prep', refreshWeather: 'Refresh weather', optimizeRoute: 'Optimize route', saveOffline: 'Save offline travel pack',
    onTrip: 'On trip', journeyTitle: 'Good morning, your next stop is ready', nextStop: 'Next stop', startNavigation: 'Start navigation', viewTickets: 'View tickets',
    translation: 'Translate', translationHelp: 'Text and useful phrases', familyShare: 'Family sharing', familyNotShared: 'Location not shared', familyShared: 'Location is being shared', allOrders: 'All bookings', ordersSubtitle: 'Hotel, transport, tickets', emergency: 'Emergency help', emergencySubtitle: 'Family, consulate, medical', todayPlan: "Today's plan",
    navPlan: 'Plan', navItinerary: 'Itinerary', navJourney: 'On trip', languageNote: 'Interface, navigation and reminders use this language. Official place names remain unchanged.', close: 'Close',
    servicesSettings: 'Services & settings', connectionCenter: 'Connection center', connectionNote: 'All demo services use one integration layer. Add production credentials to enable live search and booking.', configureLive: 'Configure live services',
    days3: '3 days', days4: '4 days', days5: '5 days', days7: '7 days', days10: '10 days', travelerCouple: '2 adults', travelerFamily: '2 adults + 2 seniors', travelerKids: '2 adults + 1 child', travelerSolo: 'Solo traveler', interestFood: 'Local food', interestCulture: 'Culture', interestNature: 'Nature', interestShopping: 'Shopping', covered: 'Included', mapNavigation: 'Maps', hotel: 'Hotels', transportTickets: 'Transport', attractionTickets: 'Attractions', weather: 'Weather', translationShort: 'Translation',
    share: 'Share', dayNumber: 'Day {number}', replace: 'Replace', viewRoute: 'View route', completed: '{done}/{total} completed', available: 'Available', added: 'Added', select: 'Select', view: 'View',
    sampleDomestic: 'Take my parents to Chengdu for 4 days, less walking, local food and culture', sampleInternational: 'Take my parents to Tokyo for 4 days, less walking, translation and airport transfer',
    promptHintDomestic: 'Travelers, duration and preferences are recognized automatically', promptHintInternational: 'Passport, visa, exchange rate, translation and safety reminders are included',
    planGenerated: 'Your complete trip is ready to edit or book', bookingConfirmed: 'Demo booking added to your itinerary', routeOptimized: 'Route optimized with less walking and fewer transfers', weatherUpdated: 'Weather and trip advice updated', offlineSaved: 'Offline pack saved: itinerary, addresses, bookings and emergency info',
    languageChanged: 'Language changed to {language}', interfaceLanguage: 'Interface language', translatedDetail: 'Route, transfers and rest time have been optimized.',
    paceRelaxed: 'Relaxed', paceBalanced: 'Classic', pacePacked: 'Full schedule', budgetValue: 'Value', budgetBalanced: 'Comfort', budgetPremium: 'Premium',
    tripTitle: '{destination} · {days} days · {pace}', tripMeta: '{date} · {people} · {budget}', people1: '1 person', people2: '2 people', people3: '3 people', people4: '4 people',
    tripDate: '{destination} · Day {day} · {date}', departAt: 'Depart {time}', navigationActive: 'Navigating · about 28 min', demoMap: 'Map navigation demo started',
    todayWalk: 'Estimated walking today', estimatedTotal: 'Estimated total', lockedCount: '{count}/4 booked', bookingAutoAdd: 'Added to the itinerary automatically'
  };

  const translations = {
    'en': en,
    'zh-CN': {
      demoRibbon: '演示环境 · 预订与实时数据为模拟结果', appName: '一路简行', chooseLanguage: '选择界面语言', scopeDomestic: '国内旅行', scopeInternational: '出境旅行', weatherSuitable: '天气适合出行',
      heroEyebrow: '国内与全球旅行，一次规划', heroTitle: '说出需求，行程就准备好了', heroSubtitle: '年轻人可以快速调整，父母也能看懂并独立使用。',
      domestic: '国内游', international: '出境游', promptLabel: '你想怎么旅行？', voiceInput: '语音说需求', confirmInfo: '确认基本信息', optional: '可选填', startDate: '出发日期', tripDays: '旅行天数', travelers: '同行人员', budget: '预算偏好', pace: '旅行节奏', interests: '希望包含', generate: '生成完整旅行方案',
      dailyPlan: '每日行程', bookingServices: '预订服务', preparation: '出行准备', refreshWeather: '更新天气', optimizeRoute: '重新优化路线', saveOffline: '保存离线旅行包', onTrip: '旅途中', journeyTitle: '上午好，下一站已准备好', nextStop: '下一站', startNavigation: '开始导航', viewTickets: '查看门票', translation: '翻译沟通', translationHelp: '文字与常用语', familyShare: '家人共享', familyNotShared: '位置尚未共享', familyShared: '位置正在共享', allOrders: '全部订单', ordersSubtitle: '酒店、交通、门票', emergency: '紧急求助', emergencySubtitle: '家人、领馆与急救', todayPlan: '今天的安排',
      navPlan: '计划', navItinerary: '行程', navJourney: '旅途中', languageNote: '界面、导航和旅行提醒将使用所选语言。景点专有名称会保留原文。', close: '关闭', servicesSettings: '服务与设置', connectionCenter: '连接中心', connectionNote: '演示版已经走通统一服务接口。配置正式密钥后，可切换到真实查询和预订。', configureLive: '配置真实服务', days3: '3天', days4: '4天', days5: '5天', days7: '7天', days10: '10天', travelerCouple: '2位成人', travelerFamily: '2位成人 + 2位长辈', travelerKids: '2位成人 + 1位儿童', travelerSolo: '1人独行', interestFood: '当地美食', interestCulture: '文化景点', interestNature: '自然风景', interestShopping: '购物', covered: '已覆盖', mapNavigation: '地图导航', hotel: '酒店', transportTickets: '交通票务', attractionTickets: '景点门票', weather: '天气', translationShort: '翻译', share: '分享', dayNumber: '第{number}天', replace: '换一个', viewRoute: '查看路线', completed: '{done}/{total} 已完成', available: '可预订', added: '已加入行程', select: '选择', view: '查看',
      sampleDomestic: '带父母去成都玩4天，少走路，想体验当地文化和美食', sampleInternational: '带父母去东京玩4天，少走路，需要中文导航、翻译和机场接送', promptHintDomestic: '系统会自动识别同行人、天数和偏好', promptHintInternational: '会自动加入护照、签证、汇率、翻译和安全提醒', planGenerated: '完整行程已生成，可继续调整或预订', bookingConfirmed: '演示预订成功，已自动加入行程', routeOptimized: '路线已优化：减少换乘并缩短步行', weatherUpdated: '天气与行程建议已更新', offlineSaved: '离线旅行包已保存：行程、地址、订单与紧急信息', languageChanged: '界面语言已切换为{language}', interfaceLanguage: '界面语言', translatedDetail: '已根据路线、换乘和休息时间优化。',
      paceRelaxed: '轻松慢游', paceBalanced: '经典适中', pacePacked: '充实行程', budgetValue: '经济省心', budgetBalanced: '舒适平衡', budgetPremium: '品质优先', tripTitle: '{destination} · {days}天{pace}', tripMeta: '{date}出发 · {people} · {budget}', people1: '1人', people2: '2人', people3: '3人', people4: '4人', tripDate: '{destination} · 第{day}天 · {date}', departAt: '{time} 出发', navigationActive: '导航中 · 约28分钟', demoMap: '地图导航演示已启动', todayWalk: '今日预计步行', estimatedTotal: '当前预估总费用', lockedCount: '已锁定 {count}/4', bookingAutoAdd: '完成后自动加入行程'
    },
    'ja': {
      demoRibbon: 'デモ環境 · 予約とリアルタイムデータは模擬です', appName: 'EasyTrip', chooseLanguage: '表示言語を選択', heroEyebrow: '国内・海外旅行をまとめて計画', heroTitle: '希望を伝えるだけで、旅程が完成', heroSubtitle: '若い方には素早く、ご両親にも分かりやすく。', domestic: '国内旅行', international: '海外旅行', promptLabel: 'どんな旅行にしますか？', voiceInput: '音声で入力', confirmInfo: '基本情報を確認', optional: '任意', startDate: '出発日', tripDays: '旅行日数', travelers: '旅行者', budget: '予算', pace: '旅行ペース', interests: '含めたいもの', generate: '旅行プランを作成', dailyPlan: '日程', bookingServices: '予約', preparation: '旅行準備', refreshWeather: '天気を更新', optimizeRoute: 'ルートを最適化', saveOffline: 'オフライン保存', onTrip: '旅行中', journeyTitle: 'おはようございます。次の目的地を準備しました', nextStop: '次の目的地', startNavigation: 'ナビ開始', viewTickets: 'チケットを見る', translation: '翻訳', translationHelp: '文章と便利なフレーズ', familyShare: '家族共有', familyNotShared: '位置情報は未共有', familyShared: '位置情報を共有中', allOrders: '予約一覧', ordersSubtitle: 'ホテル・交通・チケット', emergency: '緊急サポート', emergencySubtitle: '家族・領事館・救急', todayPlan: '今日の予定', navPlan: '計画', navItinerary: '旅程', navJourney: '旅行中', languageNote: '画面、ナビ、通知に選択言語を使用します。地名は原文を保持します。', close: '閉じる', servicesSettings: 'サービスと設定', connectionCenter: '接続センター', connectionNote: 'デモサービスは共通連携層で動作します。本番認証情報で実データに切り替えられます。', configureLive: '本番サービスを設定', share: '共有', dayNumber: '{number}日目', replace: '変更', viewRoute: 'ルート', completed: '{done}/{total} 完了', available: '予約可能', added: '追加済み', select: '選択', view: '表示', languageChanged: '{language}に切り替えました', interfaceLanguage: '表示言語', translatedDetail: '移動、乗換、休憩時間を最適化しました。', paceRelaxed: 'ゆったり', paceBalanced: '定番', pacePacked: '充実', budgetValue: '節約', budgetBalanced: '快適', budgetPremium: '上質', tripTitle: '{destination} · {days}日 · {pace}', tripMeta: '{date} · {people} · {budget}', people1: '1名', people2: '2名', people3: '3名', people4: '4名', tripDate: '{destination} · {day}日目 · {date}', departAt: '{time} 出発', todayWalk: '本日の歩行距離', estimatedTotal: '概算合計', lockedCount: '{count}/4 予約済み', bookingAutoAdd: '旅程に自動追加'
    },
    'ko': {
      demoRibbon: '데모 환경 · 예약 및 실시간 데이터는 시뮬레이션입니다', appName: 'EasyTrip', chooseLanguage: '언어 선택', heroEyebrow: '국내와 해외여행을 한 번에 계획', heroTitle: '원하는 여행을 말하면 일정이 완성됩니다', heroSubtitle: '젊은 사용자에게는 빠르고 부모님에게는 쉽습니다.', domestic: '국내 여행', international: '해외 여행', promptLabel: '어떤 여행을 원하시나요?', voiceInput: '음성으로 입력', confirmInfo: '기본 정보 확인', optional: '선택', startDate: '출발일', tripDays: '여행 기간', travelers: '여행 인원', budget: '예산', pace: '여행 속도', interests: '포함할 항목', generate: '전체 여행 계획 만들기', dailyPlan: '일정', bookingServices: '예약', preparation: '여행 준비', refreshWeather: '날씨 업데이트', optimizeRoute: '경로 최적화', saveOffline: '오프라인 저장', onTrip: '여행 중', journeyTitle: '좋은 아침입니다. 다음 목적지가 준비되었습니다', nextStop: '다음 목적지', startNavigation: '길찾기 시작', viewTickets: '티켓 보기', translation: '번역', translationHelp: '문장과 필수 표현', familyShare: '가족 공유', familyNotShared: '위치 미공유', familyShared: '위치 공유 중', allOrders: '전체 예약', ordersSubtitle: '호텔·교통·티켓', emergency: '긴급 도움', emergencySubtitle: '가족·영사관·응급', todayPlan: '오늘 일정', navPlan: '계획', navItinerary: '일정', navJourney: '여행 중', languageNote: '화면, 내비게이션과 알림에 선택한 언어를 사용합니다.', close: '닫기', servicesSettings: '서비스 및 설정', connectionCenter: '연결 센터', configureLive: '실서비스 설정', share: '공유', dayNumber: '{number}일차', replace: '변경', viewRoute: '경로 보기', completed: '{done}/{total} 완료', available: '예약 가능', added: '추가됨', select: '선택', view: '보기', languageChanged: '{language}(으)로 변경했습니다', interfaceLanguage: '인터페이스 언어', translatedDetail: '이동, 환승 및 휴식 시간을 최적화했습니다.', paceRelaxed: '여유롭게', paceBalanced: '기본', pacePacked: '알차게', budgetValue: '경제적', budgetBalanced: '편안함', budgetPremium: '프리미엄', tripTitle: '{destination} · {days}일 · {pace}', people1: '1명', people2: '2명', people3: '3명', people4: '4명', tripDate: '{destination} · {day}일차 · {date}', departAt: '{time} 출발', todayWalk: '오늘 예상 도보', estimatedTotal: '예상 총액', lockedCount: '{count}/4 예약', bookingAutoAdd: '일정에 자동 추가'
    },
    'fr': {
      demoRibbon: 'Démo · Réservations et données en temps réel simulées', appName: 'EasyTrip', chooseLanguage: 'Choisir la langue', heroEyebrow: 'Voyages nationaux et internationaux en un seul plan', heroTitle: 'Décrivez vos envies, votre voyage est prêt', heroSubtitle: 'Rapide pour les jeunes, simple et clair pour les parents.', domestic: 'National', international: 'International', promptLabel: 'Comment souhaitez-vous voyager ?', voiceInput: 'Dicter la demande', confirmInfo: 'Informations du voyage', optional: 'Facultatif', startDate: 'Date de départ', tripDays: 'Durée', travelers: 'Voyageurs', budget: 'Budget', pace: 'Rythme', interests: 'À inclure', generate: 'Créer le voyage complet', dailyPlan: 'Programme', bookingServices: 'Réservations', preparation: 'Préparation', refreshWeather: 'Actualiser la météo', optimizeRoute: 'Optimiser le trajet', saveOffline: 'Enregistrer hors ligne', onTrip: 'En voyage', journeyTitle: 'Bonjour, votre prochaine étape est prête', nextStop: 'Prochaine étape', startNavigation: 'Démarrer la navigation', viewTickets: 'Voir les billets', translation: 'Traduction', translationHelp: 'Texte et phrases utiles', familyShare: 'Partage familial', familyNotShared: 'Position non partagée', familyShared: 'Position partagée', allOrders: 'Toutes les réservations', ordersSubtitle: 'Hôtel, transport, billets', emergency: "Urgence", emergencySubtitle: 'Famille, consulat, secours', todayPlan: "Programme du jour", navPlan: 'Planifier', navItinerary: 'Itinéraire', navJourney: 'En voyage', languageNote: "L’interface, la navigation et les rappels utilisent cette langue. Les noms de lieux restent dans leur forme officielle.", close: 'Fermer', servicesSettings: 'Services et réglages', connectionCenter: 'Centre de connexion', configureLive: 'Configurer les services réels', share: 'Partager', dayNumber: 'Jour {number}', replace: 'Remplacer', viewRoute: 'Voir le trajet', completed: '{done}/{total} terminés', available: 'Disponible', added: 'Ajouté', select: 'Choisir', view: 'Voir', languageChanged: 'Langue : {language}', interfaceLanguage: "Langue de l’interface", translatedDetail: 'Trajet, correspondances et pauses optimisés.', paceRelaxed: 'Détendu', paceBalanced: 'Classique', pacePacked: 'Intensif', budgetValue: 'Économique', budgetBalanced: 'Confort', budgetPremium: 'Premium', tripTitle: '{destination} · {days} jours · {pace}', people1: '1 personne', people2: '2 personnes', people3: '3 personnes', people4: '4 personnes', tripDate: '{destination} · Jour {day} · {date}', departAt: 'Départ {time}', todayWalk: 'Marche prévue aujourd’hui', estimatedTotal: 'Total estimé', lockedCount: '{count}/4 réservés', bookingAutoAdd: "Ajout automatique à l’itinéraire"
    },
    'es': {
      demoRibbon: 'Demo · Reservas y datos en vivo simulados', appName: 'EasyTrip', chooseLanguage: 'Elegir idioma', heroEyebrow: 'Viajes nacionales e internacionales en un solo plan', heroTitle: 'Cuéntanos lo que necesitas y tu viaje estará listo', heroSubtitle: 'Rápido para jóvenes y claro para toda la familia.', domestic: 'Nacional', international: 'Internacional', promptLabel: '¿Cómo quieres viajar?', voiceInput: 'Hablar', confirmInfo: 'Datos básicos', optional: 'Opcional', startDate: 'Salida', tripDays: 'Duración', travelers: 'Viajeros', budget: 'Presupuesto', pace: 'Ritmo', interests: 'Incluir', generate: 'Crear viaje completo', dailyPlan: 'Plan diario', bookingServices: 'Reservas', preparation: 'Preparación', refreshWeather: 'Actualizar clima', optimizeRoute: 'Optimizar ruta', saveOffline: 'Guardar sin conexión', onTrip: 'En viaje', journeyTitle: 'Buenos días, tu próxima parada está lista', nextStop: 'Próxima parada', startNavigation: 'Iniciar navegación', viewTickets: 'Ver entradas', translation: 'Traducir', translationHelp: 'Texto y frases útiles', familyShare: 'Compartir con familia', familyNotShared: 'Ubicación no compartida', familyShared: 'Compartiendo ubicación', allOrders: 'Todas las reservas', ordersSubtitle: 'Hotel, transporte, entradas', emergency: 'Ayuda de emergencia', emergencySubtitle: 'Familia, consulado, urgencias', todayPlan: 'Plan de hoy', navPlan: 'Planear', navItinerary: 'Itinerario', navJourney: 'En viaje', languageNote: 'La interfaz, la navegación y los avisos usarán este idioma.', close: 'Cerrar', servicesSettings: 'Servicios y ajustes', connectionCenter: 'Centro de conexiones', configureLive: 'Configurar servicios reales', share: 'Compartir', dayNumber: 'Día {number}', replace: 'Cambiar', viewRoute: 'Ver ruta', completed: '{done}/{total} completados', available: 'Disponible', added: 'Añadido', select: 'Elegir', view: 'Ver', languageChanged: 'Idioma cambiado a {language}', interfaceLanguage: 'Idioma de la interfaz', translatedDetail: 'Ruta, transbordos y descansos optimizados.', paceRelaxed: 'Relajado', paceBalanced: 'Clásico', pacePacked: 'Completo', budgetValue: 'Económico', budgetBalanced: 'Confort', budgetPremium: 'Premium', tripTitle: '{destination} · {days} días · {pace}', people1: '1 persona', people2: '2 personas', people3: '3 personas', people4: '4 personas', tripDate: '{destination} · Día {day} · {date}', departAt: 'Salida {time}', todayWalk: 'Caminata prevista hoy', estimatedTotal: 'Total estimado', lockedCount: '{count}/4 reservados', bookingAutoAdd: 'Añadido automáticamente al itinerario'
    },
    'de': {
      demoRibbon: 'Demo · Buchungen und Live-Daten sind simuliert', appName: 'EasyTrip', chooseLanguage: 'Sprache wählen', heroEyebrow: 'Inlands- und Auslandsreisen in einem Plan', heroTitle: 'Wünsche nennen – Reiseplan fertig', heroSubtitle: 'Schnell für Jüngere, klar und einfach für Eltern.', domestic: 'Inland', international: 'International', promptLabel: 'Wie möchten Sie reisen?', voiceInput: 'Per Sprache eingeben', confirmInfo: 'Grunddaten bestätigen', optional: 'Optional', startDate: 'Abreise', tripDays: 'Reisedauer', travelers: 'Reisende', budget: 'Budget', pace: 'Reisetempo', interests: 'Einbeziehen', generate: 'Kompletten Reiseplan erstellen', dailyPlan: 'Tagesplan', bookingServices: 'Buchungen', preparation: 'Vorbereitung', refreshWeather: 'Wetter aktualisieren', optimizeRoute: 'Route optimieren', saveOffline: 'Offline speichern', onTrip: 'Unterwegs', journeyTitle: 'Guten Morgen, das nächste Ziel ist bereit', nextStop: 'Nächstes Ziel', startNavigation: 'Navigation starten', viewTickets: 'Tickets ansehen', translation: 'Übersetzen', translationHelp: 'Text und wichtige Sätze', familyShare: 'Mit Familie teilen', familyNotShared: 'Standort nicht geteilt', familyShared: 'Standort wird geteilt', allOrders: 'Alle Buchungen', ordersSubtitle: 'Hotel, Verkehr, Tickets', emergency: 'Notfallhilfe', emergencySubtitle: 'Familie, Konsulat, Rettung', todayPlan: 'Heutiger Plan', navPlan: 'Planen', navItinerary: 'Reiseplan', navJourney: 'Unterwegs', languageNote: 'Oberfläche, Navigation und Hinweise verwenden diese Sprache.', close: 'Schließen', servicesSettings: 'Dienste & Einstellungen', connectionCenter: 'Verbindungszentrum', configureLive: 'Live-Dienste konfigurieren', share: 'Teilen', dayNumber: 'Tag {number}', replace: 'Ersetzen', viewRoute: 'Route', completed: '{done}/{total} erledigt', available: 'Verfügbar', added: 'Hinzugefügt', select: 'Wählen', view: 'Ansehen', languageChanged: 'Sprache: {language}', interfaceLanguage: 'Oberflächensprache', translatedDetail: 'Route, Umstiege und Pausen wurden optimiert.', paceRelaxed: 'Entspannt', paceBalanced: 'Klassisch', pacePacked: 'Intensiv', budgetValue: 'Günstig', budgetBalanced: 'Komfort', budgetPremium: 'Premium', tripTitle: '{destination} · {days} Tage · {pace}', people1: '1 Person', people2: '2 Personen', people3: '3 Personen', people4: '4 Personen', tripDate: '{destination} · Tag {day} · {date}', departAt: 'Abfahrt {time}', todayWalk: 'Heutige Gehstrecke', estimatedTotal: 'Geschätzter Gesamtpreis', lockedCount: '{count}/4 gebucht', bookingAutoAdd: 'Automatisch zum Reiseplan hinzugefügt'
    },
    'it': {
      demoRibbon: 'Demo · Prenotazioni e dati in tempo reale simulati', appName: 'EasyTrip', chooseLanguage: 'Scegli la lingua', heroEyebrow: 'Viaggi nazionali e internazionali in un unico piano', heroTitle: 'Descrivi le tue esigenze: il viaggio è pronto', heroSubtitle: 'Veloce per i giovani, semplice e chiaro per i genitori.', domestic: 'Nazionale', international: 'Internazionale', promptLabel: 'Come vuoi viaggiare?', voiceInput: 'Inserisci con la voce', confirmInfo: 'Dati del viaggio', optional: 'Facoltativo', startDate: 'Partenza', tripDays: 'Durata', travelers: 'Viaggiatori', budget: 'Budget', pace: 'Ritmo', interests: 'Includi', generate: 'Crea il viaggio completo', dailyPlan: 'Programma', bookingServices: 'Prenotazioni', preparation: 'Preparazione', refreshWeather: 'Aggiorna meteo', optimizeRoute: 'Ottimizza percorso', saveOffline: 'Salva offline', onTrip: 'In viaggio', journeyTitle: 'Buongiorno, la prossima tappa è pronta', nextStop: 'Prossima tappa', startNavigation: 'Avvia navigazione', viewTickets: 'Vedi biglietti', translation: 'Traduci', translationHelp: 'Testo e frasi utili', familyShare: 'Condividi con famiglia', familyNotShared: 'Posizione non condivisa', familyShared: 'Posizione condivisa', allOrders: 'Tutte le prenotazioni', ordersSubtitle: 'Hotel, trasporti, biglietti', emergency: 'Aiuto urgente', emergencySubtitle: 'Famiglia, consolato, soccorso', todayPlan: 'Programma di oggi', navPlan: 'Pianifica', navItinerary: 'Itinerario', navJourney: 'In viaggio', languageNote: "L’interfaccia, la navigazione e gli avvisi useranno questa lingua.", close: 'Chiudi', servicesSettings: 'Servizi e impostazioni', connectionCenter: 'Centro connessioni', configureLive: 'Configura servizi reali', share: 'Condividi', dayNumber: 'Giorno {number}', replace: 'Sostituisci', viewRoute: 'Vedi percorso', completed: '{done}/{total} completati', available: 'Disponibile', added: 'Aggiunto', select: 'Scegli', view: 'Vedi', languageChanged: 'Lingua: {language}', interfaceLanguage: "Lingua dell’interfaccia", translatedDetail: 'Percorso, cambi e pause ottimizzati.', paceRelaxed: 'Rilassato', paceBalanced: 'Classico', pacePacked: 'Intenso', budgetValue: 'Economico', budgetBalanced: 'Comfort', budgetPremium: 'Premium', tripTitle: '{destination} · {days} giorni · {pace}', people1: '1 persona', people2: '2 persone', people3: '3 persone', people4: '4 persone', tripDate: '{destination} · Giorno {day} · {date}', departAt: 'Partenza {time}', todayWalk: 'Cammino previsto oggi', estimatedTotal: 'Totale stimato', lockedCount: '{count}/4 prenotati', bookingAutoAdd: "Aggiunta automatica all’itinerario"
    },
    'th': {
      demoRibbon: 'โหมดสาธิต · การจองและข้อมูลสดเป็นข้อมูลจำลอง', appName: 'EasyTrip', chooseLanguage: 'เลือกภาษา', heroEyebrow: 'วางแผนเที่ยวในประเทศและต่างประเทศในที่เดียว', heroTitle: 'บอกความต้องการ แล้วแผนเที่ยวก็พร้อม', heroSubtitle: 'รวดเร็วสำหรับคนรุ่นใหม่ และเข้าใจง่ายสำหรับผู้ปกครอง', domestic: 'ในประเทศ', international: 'ต่างประเทศ', promptLabel: 'คุณอยากเที่ยวแบบไหน?', voiceInput: 'พูดความต้องการ', confirmInfo: 'ยืนยันข้อมูลพื้นฐาน', optional: 'ไม่บังคับ', startDate: 'วันออกเดินทาง', tripDays: 'จำนวนวัน', travelers: 'ผู้เดินทาง', budget: 'งบประมาณ', pace: 'จังหวะการเที่ยว', interests: 'สิ่งที่ต้องการ', generate: 'สร้างแผนเที่ยวทั้งหมด', dailyPlan: 'แผนรายวัน', bookingServices: 'การจอง', preparation: 'เตรียมเดินทาง', refreshWeather: 'อัปเดตอากาศ', optimizeRoute: 'ปรับเส้นทาง', saveOffline: 'บันทึกออฟไลน์', onTrip: 'ระหว่างเดินทาง', journeyTitle: 'สวัสดี จุดหมายถัดไปพร้อมแล้ว', nextStop: 'จุดหมายถัดไป', startNavigation: 'เริ่มนำทาง', viewTickets: 'ดูตั๋ว', translation: 'แปลภาษา', translationHelp: 'ข้อความและประโยคสำคัญ', familyShare: 'แชร์กับครอบครัว', familyNotShared: 'ยังไม่แชร์ตำแหน่ง', familyShared: 'กำลังแชร์ตำแหน่ง', allOrders: 'การจองทั้งหมด', ordersSubtitle: 'โรงแรม การเดินทาง ตั๋ว', emergency: 'ช่วยเหลือฉุกเฉิน', emergencySubtitle: 'ครอบครัว สถานกงสุล การแพทย์', todayPlan: 'แผนวันนี้', navPlan: 'วางแผน', navItinerary: 'กำหนดการ', navJourney: 'กำลังเที่ยว', languageNote: 'หน้าจอ การนำทาง และการแจ้งเตือนจะใช้ภาษานี้', close: 'ปิด', servicesSettings: 'บริการและการตั้งค่า', connectionCenter: 'ศูนย์เชื่อมต่อ', configureLive: 'ตั้งค่าบริการจริง', share: 'แชร์', dayNumber: 'วันที่ {number}', replace: 'เปลี่ยน', viewRoute: 'ดูเส้นทาง', completed: 'เสร็จ {done}/{total}', available: 'จองได้', added: 'เพิ่มแล้ว', select: 'เลือก', view: 'ดู', languageChanged: 'เปลี่ยนภาษาเป็น {language}', interfaceLanguage: 'ภาษาหน้าจอ', translatedDetail: 'ปรับเส้นทาง การต่อรถ และเวลาพักแล้ว', paceRelaxed: 'สบายๆ', paceBalanced: 'มาตรฐาน', pacePacked: 'เต็มวัน', budgetValue: 'ประหยัด', budgetBalanced: 'สะดวกสบาย', budgetPremium: 'พรีเมียม', tripTitle: '{destination} · {days} วัน · {pace}', people1: '1 คน', people2: '2 คน', people3: '3 คน', people4: '4 คน', tripDate: '{destination} · วันที่ {day} · {date}', departAt: 'ออก {time}', todayWalk: 'ระยะเดินวันนี้', estimatedTotal: 'ยอดรวมโดยประมาณ', lockedCount: 'จองแล้ว {count}/4', bookingAutoAdd: 'เพิ่มในกำหนดการอัตโนมัติ'
    },
    'ar': {
      demoRibbon: 'نسخة تجريبية · الحجوزات والبيانات المباشرة محاكاة', appName: 'EasyTrip', chooseLanguage: 'اختر اللغة', heroEyebrow: 'خطّة واحدة للسفر المحلي والدولي', heroTitle: 'اذكر احتياجاتك، وستكون رحلتك جاهزة', heroSubtitle: 'سريع للشباب وواضح وسهل للوالدين.', domestic: 'محلي', international: 'دولي', promptLabel: 'كيف ترغب في السفر؟', voiceInput: 'إدخال صوتي', confirmInfo: 'تأكيد معلومات الرحلة', optional: 'اختياري', startDate: 'تاريخ المغادرة', tripDays: 'مدة الرحلة', travelers: 'المسافرون', budget: 'الميزانية', pace: 'وتيرة الرحلة', interests: 'تضمين', generate: 'إنشاء خطة الرحلة', dailyPlan: 'البرنامج اليومي', bookingServices: 'الحجوزات', preparation: 'الاستعداد', refreshWeather: 'تحديث الطقس', optimizeRoute: 'تحسين المسار', saveOffline: 'حفظ دون اتصال', onTrip: 'أثناء الرحلة', journeyTitle: 'صباح الخير، محطتك التالية جاهزة', nextStop: 'المحطة التالية', startNavigation: 'بدء الملاحة', viewTickets: 'عرض التذاكر', translation: 'الترجمة', translationHelp: 'نص وعبارات مفيدة', familyShare: 'المشاركة مع العائلة', familyNotShared: 'الموقع غير مشارك', familyShared: 'تتم مشاركة الموقع', allOrders: 'كل الحجوزات', ordersSubtitle: 'الفندق والنقل والتذاكر', emergency: 'مساعدة طارئة', emergencySubtitle: 'العائلة والقنصلية والإسعاف', todayPlan: 'خطة اليوم', navPlan: 'التخطيط', navItinerary: 'مسار الرحلة', navJourney: 'في الرحلة', languageNote: 'ستستخدم الواجهة والملاحة والتنبيهات هذه اللغة، مع إبقاء أسماء الأماكن الرسمية.', close: 'إغلاق', servicesSettings: 'الخدمات والإعدادات', connectionCenter: 'مركز الاتصال', configureLive: 'إعداد الخدمات الفعلية', share: 'مشاركة', dayNumber: 'اليوم {number}', replace: 'استبدال', viewRoute: 'عرض المسار', completed: 'اكتمل {done}/{total}', available: 'متاح', added: 'تمت الإضافة', select: 'اختيار', view: 'عرض', languageChanged: 'تم تغيير اللغة إلى {language}', interfaceLanguage: 'لغة الواجهة', translatedDetail: 'تم تحسين المسار ووسائل النقل وأوقات الراحة.', paceRelaxed: 'مريح', paceBalanced: 'متوازن', pacePacked: 'مكثف', budgetValue: 'اقتصادي', budgetBalanced: 'مريح', budgetPremium: 'مميز', tripTitle: '{destination} · {days} أيام · {pace}', people1: 'شخص واحد', people2: 'شخصان', people3: '3 أشخاص', people4: '4 أشخاص', tripDate: '{destination} · اليوم {day} · {date}', departAt: 'المغادرة {time}', todayWalk: 'المشي المتوقع اليوم', estimatedTotal: 'الإجمالي التقديري', lockedCount: 'تم حجز {count}/4', bookingAutoAdd: 'إضافة تلقائية إلى الخطة'
    },
    'ru': {
      demoRibbon: 'Демо · Бронирования и онлайн-данные смоделированы', appName: 'EasyTrip', chooseLanguage: 'Выбрать язык', heroEyebrow: 'Один план для поездок по стране и за рубеж', heroTitle: 'Расскажите о пожеланиях — маршрут готов', heroSubtitle: 'Быстро для молодых и понятно для родителей.', domestic: 'По стране', international: 'За рубеж', promptLabel: 'Как вы хотите путешествовать?', voiceInput: 'Голосовой ввод', confirmInfo: 'Основные данные', optional: 'Необязательно', startDate: 'Дата выезда', tripDays: 'Длительность', travelers: 'Путешественники', budget: 'Бюджет', pace: 'Темп', interests: 'Добавить', generate: 'Создать полный план', dailyPlan: 'План по дням', bookingServices: 'Бронирования', preparation: 'Подготовка', refreshWeather: 'Обновить погоду', optimizeRoute: 'Оптимизировать маршрут', saveOffline: 'Сохранить офлайн', onTrip: 'В поездке', journeyTitle: 'Доброе утро, следующая остановка готова', nextStop: 'Следующая остановка', startNavigation: 'Начать навигацию', viewTickets: 'Посмотреть билеты', translation: 'Перевод', translationHelp: 'Текст и полезные фразы', familyShare: 'Поделиться с семьёй', familyNotShared: 'Геопозиция не передаётся', familyShared: 'Геопозиция передаётся', allOrders: 'Все бронирования', ordersSubtitle: 'Отель, транспорт, билеты', emergency: 'Экстренная помощь', emergencySubtitle: 'Семья, консульство, медицина', todayPlan: 'План на сегодня', navPlan: 'План', navItinerary: 'Маршрут', navJourney: 'В поездке', languageNote: 'Интерфейс, навигация и уведомления будут на выбранном языке.', close: 'Закрыть', servicesSettings: 'Сервисы и настройки', connectionCenter: 'Центр подключений', configureLive: 'Настроить реальные сервисы', share: 'Поделиться', dayNumber: 'День {number}', replace: 'Заменить', viewRoute: 'Маршрут', completed: 'Выполнено {done}/{total}', available: 'Доступно', added: 'Добавлено', select: 'Выбрать', view: 'Открыть', languageChanged: 'Выбран язык: {language}', interfaceLanguage: 'Язык интерфейса', translatedDetail: 'Маршрут, пересадки и отдых оптимизированы.', paceRelaxed: 'Спокойно', paceBalanced: 'Классика', pacePacked: 'Насыщенно', budgetValue: 'Эконом', budgetBalanced: 'Комфорт', budgetPremium: 'Премиум', tripTitle: '{destination} · {days} дней · {pace}', people1: '1 человек', people2: '2 человека', people3: '3 человека', people4: '4 человека', tripDate: '{destination} · День {day} · {date}', departAt: 'Выезд в {time}', todayWalk: 'Ходьба сегодня', estimatedTotal: 'Ориентировочная сумма', lockedCount: 'Забронировано {count}/4', bookingAutoAdd: 'Автоматически добавлено в маршрут'
    },
    'pt-BR': {
      demoRibbon: 'Demo · Reservas e dados ao vivo são simulados', appName: 'EasyTrip', chooseLanguage: 'Escolher idioma', heroEyebrow: 'Viagens nacionais e internacionais em um só plano', heroTitle: 'Conte o que precisa e sua viagem estará pronta', heroSubtitle: 'Rápido para jovens e claro para toda a família.', domestic: 'Nacional', international: 'Internacional', promptLabel: 'Como você quer viajar?', voiceInput: 'Falar pedido', confirmInfo: 'Dados básicos', optional: 'Opcional', startDate: 'Data de saída', tripDays: 'Duração', travelers: 'Viajantes', budget: 'Orçamento', pace: 'Ritmo', interests: 'Incluir', generate: 'Criar viagem completa', dailyPlan: 'Plano diário', bookingServices: 'Reservas', preparation: 'Preparação', refreshWeather: 'Atualizar clima', optimizeRoute: 'Otimizar rota', saveOffline: 'Salvar offline', onTrip: 'Em viagem', journeyTitle: 'Bom dia, sua próxima parada está pronta', nextStop: 'Próxima parada', startNavigation: 'Iniciar navegação', viewTickets: 'Ver ingressos', translation: 'Traduzir', translationHelp: 'Texto e frases úteis', familyShare: 'Compartilhar com família', familyNotShared: 'Localização não compartilhada', familyShared: 'Compartilhando localização', allOrders: 'Todas as reservas', ordersSubtitle: 'Hotel, transporte, ingressos', emergency: 'Ajuda de emergência', emergencySubtitle: 'Família, consulado, emergência', todayPlan: 'Plano de hoje', navPlan: 'Planejar', navItinerary: 'Roteiro', navJourney: 'Em viagem', languageNote: 'A interface, a navegação e os avisos usarão este idioma.', close: 'Fechar', servicesSettings: 'Serviços e ajustes', connectionCenter: 'Central de conexões', configureLive: 'Configurar serviços reais', share: 'Compartilhar', dayNumber: 'Dia {number}', replace: 'Trocar', viewRoute: 'Ver rota', completed: '{done}/{total} concluídos', available: 'Disponível', added: 'Adicionado', select: 'Escolher', view: 'Ver', languageChanged: 'Idioma alterado para {language}', interfaceLanguage: 'Idioma da interface', translatedDetail: 'Rota, conexões e pausas foram otimizadas.', paceRelaxed: 'Tranquilo', paceBalanced: 'Clássico', pacePacked: 'Intenso', budgetValue: 'Econômico', budgetBalanced: 'Conforto', budgetPremium: 'Premium', tripTitle: '{destination} · {days} dias · {pace}', people1: '1 pessoa', people2: '2 pessoas', people3: '3 pessoas', people4: '4 pessoas', tripDate: '{destination} · Dia {day} · {date}', departAt: 'Saída {time}', todayWalk: 'Caminhada prevista hoje', estimatedTotal: 'Total estimado', lockedCount: '{count}/4 reservados', bookingAutoAdd: 'Adicionado automaticamente ao roteiro'
    }
  };

  Object.assign(en, {
    routeMap: 'Daily route map', walking: 'Walk', transit: 'Transit', driving: 'Drive', loadingMap: 'Loading map…', openLocalMap: 'Open in map',
    mapModeReady: '{mode} route selected', liveMap: 'Live map', fallbackMap: 'Preview + external navigation', amapRouteReady: 'AMap route preview is ready',
    googleRouteReady: 'Google Maps route preview is ready', amapExternalReady: 'Preview shown · navigation opens in AMap',
    googleExternalReady: 'Preview shown · navigation opens in Google Maps', mapNeedsKey: 'Add a map API key to show the interactive map',
    mapLoadFailed: 'The online map could not load. External navigation is still available.'
  });

  Object.assign(en, {
    familyCenterEyebrow: 'Travel together, stay connected', familyCenterTitle: 'Family sharing center', familyMembers: 'Family members', familyPrivacy: 'Visible to invited members only',
    familyInviteLabel: 'Name or phone', familyInvitePlaceholder: 'e.g. Mom', familyRelation: 'Relationship', relationFamily: 'Family', relationPartner: 'Partner', relationFriend: 'Friend', addMember: 'Add',
    sharingContent: 'What to share', shareItinerary: 'Daily itinerary', shareItineraryHelp: 'Stops, times and transport', shareLocation: 'Live location', shareLocationHelp: 'Demo location, updated only during the trip',
    shareBookings: 'Bookings and tickets', shareBookingsHelp: 'View only; payment details stay hidden', shareAlerts: 'Safety alerts', shareAlertsHelp: 'Delays, changes and emergency notices',
    shareUntil: 'Share until', untilTripEnd: 'End of this trip', until24Hours: 'Next 24 hours', untilManual: 'Until I turn it off', sendCheckIn: "I'm safe", copyInvite: 'Copy invite',
    startFamilySharing: 'Start family sharing', updateFamilySharing: 'Save sharing settings', stopFamilySharing: 'Pause all sharing', familyMemberMother: 'Mom', familyMemberBrother: 'Brother',
    familyMemberCount: '{count} members', familySummaryOff: 'Sharing is off', familySummaryActive: 'Family sharing is on', familySummaryMeta: '{count} invited members can view updates', familyBadgeOn: 'Sharing', familyBadgeOff: 'Off',
    memberJoined: 'Joined', memberInvited: 'Invite sent', removeMember: 'Remove member', familyNoMembers: 'Add at least one family member', familyPlanShared: 'Itinerary shared with {count} family members',
    familyCheckInNone: 'No safety check-in sent yet', familyCheckInSent: 'Safety check-in sent at {time}', familyPrivacyNote: 'Pause sharing at any time. This demo does not upload your location to a server.',
    familySelectOne: 'Choose at least one item to share', familyMemberAdded: 'Member added and invite prepared', familySharingSaved: 'Family sharing settings saved', familySharingStopped: 'All family sharing paused',
    familyCheckInDelivered: 'Safety check-in sent to {count} family members', familyInviteCopied: 'Family invite copied', familyInviteMessage: 'View my {destination} trip and safety updates:'
  });

  Object.assign(translations['zh-CN'], {
    routeMap: '当日路线地图', walking: '步行', transit: '公交', driving: '驾车', loadingMap: '正在加载地图…', openLocalMap: '在地图中打开',
    mapModeReady: '已选择{mode}路线', liveMap: '实时地图', fallbackMap: '路线预览 + 外部导航', amapRouteReady: '高德地图路线已准备',
    googleRouteReady: 'Google Maps 路线已准备', amapExternalReady: '当前为路线预览，导航将在高德地图打开',
    googleExternalReady: '当前为路线预览，导航将在 Google Maps 打开', mapNeedsKey: '配置地图 API 密钥后可显示交互地图',
    mapLoadFailed: '在线地图加载失败，仍可使用外部导航'
  });

  Object.assign(en, {
    viewSetupGuide: 'View production setup guide', integrationMaps: 'Maps & routes', integrationAmap: 'AMap in China · OSM preview fallback', integrationGoogle: 'Google Maps overseas · OSM preview fallback',
    integrationFamily: 'Family chat', integrationFamilyDetail: 'Account, family room, messages and shared trips', integrationOffline: 'Offline travel pack', integrationOfflineDetail: 'Itinerary, bookings and emergency details on this device',
    integrationLanguage: 'Languages & voice', integrationLanguageDetail: '12 interface languages with RTL support', integrationBooking: 'Live bookings', integrationBookingDetail: 'Supplier contracts and a secure server are required',
    statusLive: 'Live', statusPreviewReady: 'Preview ready', statusNeedsSetup: 'Setup needed', statusCloudReady: 'Cloud ready', statusLocalReady: 'Local ready', statusSaved: 'Saved', statusAvailable: 'Available', statusReady: 'Ready', statusDemoOnly: 'Demo only',
    offlineSaveFailed: 'The offline pack could not be saved on this device'
  });

  Object.assign(translations['zh-CN'], {
    viewSetupGuide: '查看正式服务接入说明', integrationMaps: '地图与路线', integrationAmap: '中国使用高德 · 无密钥时显示路线预览', integrationGoogle: '海外使用 Google Maps · 无密钥时显示路线预览',
    integrationFamily: '家庭群聊', integrationFamilyDetail: '账号、家庭房间、消息和行程共享', integrationOffline: '离线旅行包', integrationOfflineDetail: '行程、订单选择和紧急信息保存在本机',
    integrationLanguage: '多语言与语音', integrationLanguageDetail: '12种界面语言并支持阿拉伯语布局', integrationBooking: '真实预订', integrationBookingDetail: '需要供应商商务授权和安全后端',
    statusLive: '实时已连接', statusPreviewReady: '预览可用', statusNeedsSetup: '需要配置', statusCloudReady: '云端可用', statusLocalReady: '本机可用', statusSaved: '已保存', statusAvailable: '可以使用', statusReady: '已就绪', statusDemoOnly: '仅演示',
    offlineSaveFailed: '当前设备无法保存离线旅行包'
  });

  Object.assign(en, {
    localProfile: '{country} · {currency} · {timeZone} · {map}', localEstimate: 'Demo estimate in local currency',
    emergencyHelp: 'Emergency help', emergencyWho: 'Who do you need to contact?', emergencyRegion: 'Destination: {country}',
    contactFamily: 'Contact family', contactFamilyHelp: 'Share your location and itinerary', generalEmergency: 'General emergency',
    medicalEmergency: 'Medical emergency', policeEmergency: 'Police', fireEmergency: 'Fire & rescue', callNumber: 'Call {number}',
    consularHelp: 'Consular assistance', consularHelpDetail: 'View help for your destination', officialEmergencySource: 'View official local number source'
  });

  Object.assign(translations['zh-CN'], {
    localProfile: '{country} · {currency} · {timeZone} · {map}', localEstimate: '当地货币演示估算',
    emergencyHelp: '紧急帮助', emergencyWho: '你需要联系谁？', emergencyRegion: '当前目的地：{country}',
    contactFamily: '联系家人', contactFamilyHelp: '发送当前位置与行程', generalEmergency: '综合紧急求助',
    medicalEmergency: '医疗急救', policeEmergency: '警察', fireEmergency: '消防救援', callNumber: '拨打 {number}',
    consularHelp: '领事保护', consularHelpDetail: '查看目的地领事协助信息', officialEmergencySource: '查看当地官方号码来源'
  });

  Object.assign(translations['zh-CN'], {
    familyCenterEyebrow: '亲友同行保障', familyCenterTitle: '家庭共享中心', familyMembers: '家庭成员', familyPrivacy: '只有受邀成员可以查看',
    familyInviteLabel: '姓名或手机号', familyInvitePlaceholder: '例如：妈妈', familyRelation: '关系', relationFamily: '家人', relationPartner: '伴侣', relationFriend: '朋友', addMember: '添加',
    sharingContent: '共享内容', shareItinerary: '每日行程', shareItineraryHelp: '景点、时间和交通安排', shareLocation: '实时位置', shareLocationHelp: '演示位置，仅在旅途中更新',
    shareBookings: '订单与票券', shareBookingsHelp: '仅查看，不显示支付信息', shareAlerts: '安全提醒', shareAlertsHelp: '延误、行程变化和紧急通知',
    shareUntil: '共享时间', untilTripEnd: '本次旅行结束', until24Hours: '未来24小时', untilManual: '手动关闭', sendCheckIn: '我已平安', copyInvite: '复制邀请',
    startFamilySharing: '开启家庭共享', updateFamilySharing: '保存共享设置', stopFamilySharing: '暂停全部共享', familyMemberMother: '妈妈', familyMemberBrother: '弟弟',
    familyMemberCount: '{count}位', familySummaryOff: '尚未开启共享', familySummaryActive: '家庭共享已开启', familySummaryMeta: '{count}位受邀成员可以查看动态', familyBadgeOn: '共享中', familyBadgeOff: '未共享',
    memberJoined: '已加入', memberInvited: '邀请已发送', removeMember: '移除成员', familyNoMembers: '请至少添加一位家庭成员', familyPlanShared: '已向{count}位家人共享行程',
    familyCheckInNone: '还没有发送报平安消息', familyCheckInSent: '{time} 已向家人报平安', familyPrivacyNote: '你可以随时暂停共享。演示版不会将位置发送到服务器。',
    familySelectOne: '请至少选择一项共享内容', familyMemberAdded: '已添加成员并准备邀请', familySharingSaved: '家庭共享设置已保存', familySharingStopped: '已暂停全部家庭共享',
    familyCheckInDelivered: '已向{count}位家人发送“我已平安”', familyInviteCopied: '家庭邀请已复制', familyInviteMessage: '查看我的{destination}行程和安全动态：'
  });

  Object.assign(en, {
    familyChat: 'Family chat', navFamily: 'Family', familySpace: 'Family Space', familyChatTitle: 'Family chat', familyChatSubtitle: 'Join one family to chat, view trips and check in safely.',
    registerAccount: 'Create account', loginAccount: 'Log in', familyAccount: 'Family account', demoAccountNote: 'This demo account stays on this device. Do not enter sensitive personal information.', cloudAccountNote: 'Cloud account: use email worldwide or a +86 mobile number. Your family data syncs across devices.',
    cloudConnectedLabel: 'Cloud sync', localDemoLabel: 'Local demo', familyCloudConnecting: 'Connecting to family cloud…', verificationCodeSent: 'Verification code sent. Please check your messages.',
    nickname: 'Your name', phoneOrEmail: 'Phone or email', verificationCode: 'Verification code', getCode: 'Get code', registerAndContinue: 'Create account and continue', loginAndContinue: 'Log in and continue',
    logoutAccount: 'Log out', createOrJoinFamily: 'Create or join a family', familyEntryHelp: 'Use the same invite code to enter one family chat.', createFamily: 'Create family', familyName: 'Family name',
    createAndEnter: 'Create and enter', joinFamily: 'Join with invite code', inviteCode: 'Family invite code', joinAndEnter: 'Join family', copyInviteCode: 'Copy invite code', leaveFamily: 'Leave family',
    shareCurrentTrip: 'Share current trip in chat', messagePlaceholder: 'Enter a message', sendMessage: 'Send', familyChatLoginHint: 'Log in to enter family chat', familyNoRoomHint: 'Create or join a family', familyRoomStatus: '{count} members in family chat',
    nicknamePlaceholder: 'e.g. Alex', accountPlaceholder: 'Used to log in', loginAccountPlaceholder: 'Enter your registered account', codePlaceholder: '6 digits', travelerName: 'Traveler', familyNamePlaceholder: 'e.g. Our Happy Family', inviteCodePlaceholder: 'e.g. ET2026',
    sharedTripTitle: '{destination} family trip', tripDaysCount: '{count} days', viewFullTrip: 'View full itinerary', me: 'Me', familyRoomMeta: '{count} members · {online} online', chatInputPlaceholder: 'Message your family…',
    chatEmptyTitle: 'The family chat is ready', chatEmptyHelp: 'Send a message or share your current trip.', tripSharedToFamily: 'Trip shared in the family chat', demoCodeSent: 'Demo code filled in: {code}', completeAccountInfo: 'Please enter your name and account',
    codeIncorrect: 'Use the demo verification code 123456', accountCreated: 'Account created', accountNotFound: 'No local account found. Please create one first.', loginSuccessful: 'Logged in', enterFamilyName: 'Enter a family name', invalidContact: 'Enter a valid email address or mainland China mobile number', overseasPhoneEmailHint: 'International SMS is not enabled yet. Please use email for this pilot.', requestCodeFirst: 'Request a verification code first', familyNotFound: 'No family was found for this invite code', alreadyInFamily: 'Leave the current family before joining another one', cloudUnavailable: 'The family cloud is temporarily unavailable. Please try again later.', realtimeDisconnected: 'Live chat connection was interrupted. Reopen the family page to reconnect.', tripPlanFallback: 'Travel plan',
    familyCreatedMessage: '{name} was created. Copy the invite code for your family.', familyCreated: 'Family created', enterValidInviteCode: 'Enter a valid family invite code', demoFamilyName: 'Our Family', joinedFamilyMessage: 'You joined the family chat',
    familyWelcomeMessage: 'I am here. You can share the travel plan in this chat.', joinedFamily: 'Joined the family', familyAutoReply: 'Got it. I can see the message and itinerary here.', enterFamilyBeforeShare: 'Log in and enter a family before sharing',
    familyInviteChatMessage: 'Join “{family}” in EasyTrip with invite code: {code}', inviteCodeCopied: 'Invite code copied: {code}', leftFamily: 'You left the family'
  });

  Object.assign(translations['zh-CN'], {
    familyChat: '家庭群聊', navFamily: '家庭', familySpace: 'Family Space · 家庭空间', familyChatTitle: '家庭群聊', familyChatSubtitle: '一家人进入同一个家庭，聊天、看行程、互相报平安。',
    registerAccount: '注册账号', loginAccount: '登录', familyAccount: '家庭账号', demoAccountNote: '演示账号只保存在本机，请勿填写真实敏感信息。', cloudAccountNote: '云端账号：全球可用邮箱验证码，中国大陆可用 +86 手机验证码；家庭数据会跨设备同步。',
    cloudConnectedLabel: '云端同步', localDemoLabel: '本机演示', familyCloudConnecting: '正在连接家庭云端…', verificationCodeSent: '验证码已发送，请查看短信或邮箱。',
    nickname: '你的称呼', phoneOrEmail: '手机号或邮箱', verificationCode: '验证码', getCode: '获取验证码', registerAndContinue: '注册并继续', loginAndContinue: '登录并继续',
    logoutAccount: '退出账号', createOrJoinFamily: '创建或加入一个家庭', familyEntryHelp: '家人使用同一个邀请码，就能进入同一个聊天室。', createFamily: '创建家庭', familyName: '家庭名称',
    createAndEnter: '创建并进入', joinFamily: '使用邀请码加入', inviteCode: '家庭邀请码', joinAndEnter: '加入家庭', copyInviteCode: '复制邀请码', leaveFamily: '退出家庭',
    shareCurrentTrip: '把当前行程发到群里', messagePlaceholder: '输入消息', sendMessage: '发送', familyChatLoginHint: '登录后进入家庭群聊', familyNoRoomHint: '创建或加入一个家庭', familyRoomStatus: '家庭群聊 · {count}位成员',
    nicknamePlaceholder: '例如：小林', accountPlaceholder: '用于登录家庭', loginAccountPlaceholder: '输入已注册账号', codePlaceholder: '6位数字', travelerName: '旅行者', familyNamePlaceholder: '例如：幸福一家', inviteCodePlaceholder: '例如：ET2026',
    sharedTripTitle: '{destination}家庭旅行', tripDaysCount: '{count}天旅行计划', viewFullTrip: '查看完整行程', me: '我', familyRoomMeta: '{count}位成员 · {online}人在线', chatInputPlaceholder: '发消息给家人…',
    chatEmptyTitle: '家庭聊天室已准备好', chatEmptyHelp: '发送一句话，或者把当前旅行计划分享进来。', tripSharedToFamily: '行程已发送到家庭群聊', demoCodeSent: '演示验证码已填入：{code}', completeAccountInfo: '请填写称呼和登录账号',
    codeIncorrect: '请输入演示验证码 123456', accountCreated: '账号注册成功', accountNotFound: '本机没有这个账号，请先注册', loginSuccessful: '登录成功', enterFamilyName: '请输入家庭名称', invalidContact: '请输入有效的邮箱或中国大陆手机号', overseasPhoneEmailHint: '第一阶段暂未开通国际短信，请使用邮箱验证码。', requestCodeFirst: '请先获取验证码', familyNotFound: '没有找到这个邀请码对应的家庭', alreadyInFamily: '请先退出当前家庭，再加入其他家庭', cloudUnavailable: '家庭云服务暂时无法连接，请稍后再试。', realtimeDisconnected: '实时聊天连接已中断，请重新进入家庭页面。', tripPlanFallback: '旅行计划',
    familyCreatedMessage: '“{name}”已创建，把邀请码发给家人即可加入。', familyCreated: '家庭创建成功', enterValidInviteCode: '请输入有效的家庭邀请码', demoFamilyName: '温暖一家', joinedFamilyMessage: '你已加入家庭群聊',
    familyWelcomeMessage: '我已经进来了，旅行计划发在这里就可以。', joinedFamily: '已加入家庭', familyAutoReply: '收到，我能在这里看到消息和行程。', enterFamilyBeforeShare: '请先登录并进入一个家庭',
    familyInviteChatMessage: '邀请你加入一路简行的“{family}”，家庭邀请码：{code}', inviteCodeCopied: '邀请码已复制：{code}', leftFamily: '已退出家庭'
  });

  const familyLocalePacks = {
    ja: {
      familyCenterEyebrow: '家族とつながる安心機能', familyCenterTitle: '家族共有センター', familyMembers: '家族メンバー', familyPrivacy: '招待されたメンバーだけが閲覧できます', familyInviteLabel: '名前または電話番号', familyInvitePlaceholder: '例：母', familyRelation: '関係', relationFamily: '家族', relationPartner: 'パートナー', relationFriend: '友人', addMember: '追加', sharingContent: '共有する内容', shareItinerary: '毎日の予定', shareLocation: '現在地', shareBookings: '予約とチケット', shareAlerts: '安全通知', shareUntil: '共有期間', untilTripEnd: '旅行終了まで', until24Hours: '24時間', untilManual: '手動で停止するまで', sendCheckIn: '無事です', copyInvite: '招待をコピー', startFamilySharing: '家族共有を開始', updateFamilySharing: '共有設定を保存', stopFamilySharing: 'すべての共有を停止', familyMemberMother: '母', familyMemberBrother: '弟', familyBadgeOn: '共有中', familyBadgeOff: '停止中', familySummaryOff: '共有は停止中です', familySummaryActive: '家族共有中', memberJoined: '参加済み', memberInvited: '招待済み', removeMember: 'メンバーを削除', familyNoMembers: '家族を1人以上追加してください', familyMemberCount: '{count}人', familyPlanShared: '{count}人の家族と予定を共有中'
    },
    ko: {
      familyCenterEyebrow: '가족과 함께하는 안심 여행', familyCenterTitle: '가족 공유 센터', familyMembers: '가족 구성원', familyPrivacy: '초대된 구성원만 볼 수 있습니다', familyInviteLabel: '이름 또는 전화번호', familyInvitePlaceholder: '예: 엄마', familyRelation: '관계', relationFamily: '가족', relationPartner: '파트너', relationFriend: '친구', addMember: '추가', sharingContent: '공유 항목', shareItinerary: '일일 일정', shareLocation: '실시간 위치', shareBookings: '예약 및 티켓', shareAlerts: '안전 알림', shareUntil: '공유 기간', untilTripEnd: '여행 종료까지', until24Hours: '24시간', untilManual: '직접 끌 때까지', sendCheckIn: '저는 안전해요', copyInvite: '초대 복사', startFamilySharing: '가족 공유 시작', updateFamilySharing: '공유 설정 저장', stopFamilySharing: '모든 공유 중지', familyMemberMother: '엄마', familyMemberBrother: '남동생', familyBadgeOn: '공유 중', familyBadgeOff: '꺼짐', familySummaryOff: '공유가 꺼져 있습니다', familySummaryActive: '가족 공유 중', memberJoined: '참여함', memberInvited: '초대 보냄', removeMember: '구성원 삭제', familyNoMembers: '가족을 한 명 이상 추가하세요', familyMemberCount: '{count}명', familyPlanShared: '가족 {count}명과 일정 공유 중'
    },
    fr: {
      familyCenterEyebrow: 'Voyager ensemble, rester proches', familyCenterTitle: 'Partage familial', familyMembers: 'Membres de la famille', familyPrivacy: 'Visible uniquement par les membres invités', familyInviteLabel: 'Nom ou téléphone', familyInvitePlaceholder: 'Ex. Maman', familyRelation: 'Relation', relationFamily: 'Famille', relationPartner: 'Partenaire', relationFriend: 'Ami', addMember: 'Ajouter', sharingContent: 'Éléments partagés', shareItinerary: 'Programme quotidien', shareLocation: 'Position en direct', shareBookings: 'Réservations et billets', shareAlerts: 'Alertes de sécurité', shareUntil: 'Partager jusqu’à', untilTripEnd: 'Fin du voyage', until24Hours: '24 prochaines heures', untilManual: 'Désactivation manuelle', sendCheckIn: 'Je vais bien', copyInvite: 'Copier l’invitation', startFamilySharing: 'Activer le partage', updateFamilySharing: 'Enregistrer les réglages', stopFamilySharing: 'Suspendre tout partage', familyMemberMother: 'Maman', familyMemberBrother: 'Frère', familyBadgeOn: 'Partagé', familyBadgeOff: 'Arrêté', familySummaryOff: 'Partage désactivé', familySummaryActive: 'Partage familial actif', memberJoined: 'A rejoint', memberInvited: 'Invitation envoyée', removeMember: 'Supprimer le membre', familyNoMembers: 'Ajoutez au moins un membre', familyMemberCount: '{count} membres', familyPlanShared: 'Programme partagé avec {count} proches'
    },
    es: {
      familyCenterEyebrow: 'Viajar juntos y conectados', familyCenterTitle: 'Centro familiar', familyMembers: 'Miembros de la familia', familyPrivacy: 'Solo visible para miembros invitados', familyInviteLabel: 'Nombre o teléfono', familyInvitePlaceholder: 'Ej.: Mamá', familyRelation: 'Relación', relationFamily: 'Familia', relationPartner: 'Pareja', relationFriend: 'Amigo', addMember: 'Añadir', sharingContent: 'Qué compartir', shareItinerary: 'Plan diario', shareLocation: 'Ubicación en vivo', shareBookings: 'Reservas y entradas', shareAlerts: 'Alertas de seguridad', shareUntil: 'Compartir hasta', untilTripEnd: 'Fin del viaje', until24Hours: 'Próximas 24 horas', untilManual: 'Hasta desactivarlo', sendCheckIn: 'Estoy bien', copyInvite: 'Copiar invitación', startFamilySharing: 'Activar uso compartido', updateFamilySharing: 'Guardar ajustes', stopFamilySharing: 'Pausar todo', familyMemberMother: 'Mamá', familyMemberBrother: 'Hermano', familyBadgeOn: 'Compartiendo', familyBadgeOff: 'Desactivado', familySummaryOff: 'Uso compartido desactivado', familySummaryActive: 'Uso compartido activo', memberJoined: 'Se unió', memberInvited: 'Invitación enviada', removeMember: 'Eliminar miembro', familyNoMembers: 'Añade al menos un familiar', familyMemberCount: '{count} miembros', familyPlanShared: 'Plan compartido con {count} familiares'
    },
    de: {
      familyCenterEyebrow: 'Gemeinsam reisen, verbunden bleiben', familyCenterTitle: 'Familienfreigabe', familyMembers: 'Familienmitglieder', familyPrivacy: 'Nur für eingeladene Mitglieder sichtbar', familyInviteLabel: 'Name oder Telefonnummer', familyInvitePlaceholder: 'z. B. Mama', familyRelation: 'Beziehung', relationFamily: 'Familie', relationPartner: 'Partner', relationFriend: 'Freund', addMember: 'Hinzufügen', sharingContent: 'Freigabeinhalte', shareItinerary: 'Tagesplan', shareLocation: 'Live-Standort', shareBookings: 'Buchungen und Tickets', shareAlerts: 'Sicherheitshinweise', shareUntil: 'Teilen bis', untilTripEnd: 'Reiseende', until24Hours: 'Nächste 24 Stunden', untilManual: 'Manuell beenden', sendCheckIn: 'Mir geht es gut', copyInvite: 'Einladung kopieren', startFamilySharing: 'Familienfreigabe starten', updateFamilySharing: 'Einstellungen speichern', stopFamilySharing: 'Alles pausieren', familyMemberMother: 'Mama', familyMemberBrother: 'Bruder', familyBadgeOn: 'Aktiv', familyBadgeOff: 'Aus', familySummaryOff: 'Freigabe ist aus', familySummaryActive: 'Familienfreigabe ist aktiv', memberJoined: 'Beigetreten', memberInvited: 'Einladung gesendet', removeMember: 'Mitglied entfernen', familyNoMembers: 'Mindestens ein Mitglied hinzufügen', familyMemberCount: '{count} Mitglieder', familyPlanShared: 'Plan mit {count} Angehörigen geteilt'
    },
    it: {
      familyCenterEyebrow: 'Viaggiare insieme e restare vicini', familyCenterTitle: 'Condivisione famiglia', familyMembers: 'Membri della famiglia', familyPrivacy: 'Visibile solo ai membri invitati', familyInviteLabel: 'Nome o telefono', familyInvitePlaceholder: 'Es. Mamma', familyRelation: 'Relazione', relationFamily: 'Famiglia', relationPartner: 'Partner', relationFriend: 'Amico', addMember: 'Aggiungi', sharingContent: 'Cosa condividere', shareItinerary: 'Programma giornaliero', shareLocation: 'Posizione in tempo reale', shareBookings: 'Prenotazioni e biglietti', shareAlerts: 'Avvisi di sicurezza', shareUntil: 'Condividi fino a', untilTripEnd: 'Fine del viaggio', until24Hours: 'Prossime 24 ore', untilManual: 'Disattivazione manuale', sendCheckIn: 'Sto bene', copyInvite: 'Copia invito', startFamilySharing: 'Avvia condivisione', updateFamilySharing: 'Salva impostazioni', stopFamilySharing: 'Sospendi tutto', familyMemberMother: 'Mamma', familyMemberBrother: 'Fratello', familyBadgeOn: 'Attiva', familyBadgeOff: 'Disattiva', familySummaryOff: 'Condivisione disattivata', familySummaryActive: 'Condivisione famiglia attiva', memberJoined: 'Partecipante', memberInvited: 'Invito inviato', removeMember: 'Rimuovi membro', familyNoMembers: 'Aggiungi almeno un familiare', familyMemberCount: '{count} membri', familyPlanShared: 'Programma condiviso con {count} familiari'
    },
    th: {
      familyCenterEyebrow: 'เที่ยวด้วยกันและไม่ขาดการติดต่อ', familyCenterTitle: 'ศูนย์แชร์กับครอบครัว', familyMembers: 'สมาชิกครอบครัว', familyPrivacy: 'เฉพาะสมาชิกที่ได้รับเชิญเท่านั้น', familyInviteLabel: 'ชื่อหรือเบอร์โทร', familyInvitePlaceholder: 'เช่น แม่', familyRelation: 'ความสัมพันธ์', relationFamily: 'ครอบครัว', relationPartner: 'คู่ชีวิต', relationFriend: 'เพื่อน', addMember: 'เพิ่ม', sharingContent: 'สิ่งที่แชร์', shareItinerary: 'แผนรายวัน', shareLocation: 'ตำแหน่งสด', shareBookings: 'การจองและตั๋ว', shareAlerts: 'แจ้งเตือนความปลอดภัย', shareUntil: 'แชร์จนถึง', untilTripEnd: 'จบทริปนี้', until24Hours: '24 ชั่วโมง', untilManual: 'จนกว่าจะปิดเอง', sendCheckIn: 'ฉันปลอดภัย', copyInvite: 'คัดลอกคำเชิญ', startFamilySharing: 'เริ่มแชร์กับครอบครัว', updateFamilySharing: 'บันทึกการตั้งค่า', stopFamilySharing: 'หยุดแชร์ทั้งหมด', familyMemberMother: 'แม่', familyMemberBrother: 'น้องชาย', familyBadgeOn: 'กำลังแชร์', familyBadgeOff: 'ปิด', familySummaryOff: 'ปิดการแชร์อยู่', familySummaryActive: 'กำลังแชร์กับครอบครัว', memberJoined: 'เข้าร่วมแล้ว', memberInvited: 'ส่งคำเชิญแล้ว', removeMember: 'ลบสมาชิก', familyNoMembers: 'เพิ่มสมาชิกอย่างน้อยหนึ่งคน', familyMemberCount: '{count} คน', familyPlanShared: 'แชร์แผนกับครอบครัว {count} คน'
    },
    ar: {
      familyCenterEyebrow: 'سافروا معًا وابقوا على تواصل', familyCenterTitle: 'مركز المشاركة العائلية', familyMembers: 'أفراد العائلة', familyPrivacy: 'مرئي للأعضاء المدعوين فقط', familyInviteLabel: 'الاسم أو رقم الهاتف', familyInvitePlaceholder: 'مثال: أمي', familyRelation: 'العلاقة', relationFamily: 'العائلة', relationPartner: 'الشريك', relationFriend: 'صديق', addMember: 'إضافة', sharingContent: 'المحتوى المشترك', shareItinerary: 'الخطة اليومية', shareLocation: 'الموقع المباشر', shareBookings: 'الحجوزات والتذاكر', shareAlerts: 'تنبيهات السلامة', shareUntil: 'المشاركة حتى', untilTripEnd: 'نهاية الرحلة', until24Hours: '24 ساعة', untilManual: 'حتى إيقافها', sendCheckIn: 'أنا بخير', copyInvite: 'نسخ الدعوة', startFamilySharing: 'بدء المشاركة العائلية', updateFamilySharing: 'حفظ الإعدادات', stopFamilySharing: 'إيقاف كل المشاركة', familyMemberMother: 'أمي', familyMemberBrother: 'أخي', familyBadgeOn: 'قيد المشاركة', familyBadgeOff: 'متوقفة', familySummaryOff: 'المشاركة متوقفة', familySummaryActive: 'المشاركة العائلية مفعلة', memberJoined: 'انضم', memberInvited: 'تم إرسال الدعوة', removeMember: 'إزالة العضو', familyNoMembers: 'أضف فردًا واحدًا على الأقل', familyMemberCount: '{count} أعضاء', familyPlanShared: 'تمت مشاركة الخطة مع {count} من العائلة'
    },
    ru: {
      familyCenterEyebrow: 'Путешествуйте вместе и оставайтесь на связи', familyCenterTitle: 'Семейный доступ', familyMembers: 'Члены семьи', familyPrivacy: 'Доступно только приглашённым', familyInviteLabel: 'Имя или телефон', familyInvitePlaceholder: 'Например, мама', familyRelation: 'Отношение', relationFamily: 'Семья', relationPartner: 'Партнёр', relationFriend: 'Друг', addMember: 'Добавить', sharingContent: 'Что показывать', shareItinerary: 'План на день', shareLocation: 'Геопозиция', shareBookings: 'Брони и билеты', shareAlerts: 'Оповещения безопасности', shareUntil: 'Делиться до', untilTripEnd: 'Конца поездки', until24Hours: '24 часа', untilManual: 'Ручного отключения', sendCheckIn: 'Я в порядке', copyInvite: 'Копировать приглашение', startFamilySharing: 'Включить семейный доступ', updateFamilySharing: 'Сохранить настройки', stopFamilySharing: 'Остановить весь доступ', familyMemberMother: 'Мама', familyMemberBrother: 'Брат', familyBadgeOn: 'Доступ открыт', familyBadgeOff: 'Выключено', familySummaryOff: 'Доступ выключен', familySummaryActive: 'Семейный доступ включён', memberJoined: 'Присоединился', memberInvited: 'Приглашение отправлено', removeMember: 'Удалить участника', familyNoMembers: 'Добавьте хотя бы одного человека', familyMemberCount: '{count} участников', familyPlanShared: 'План доступен {count} близким'
    },
    'pt-BR': {
      familyCenterEyebrow: 'Viajem juntos e conectados', familyCenterTitle: 'Central da família', familyMembers: 'Membros da família', familyPrivacy: 'Visível apenas para membros convidados', familyInviteLabel: 'Nome ou telefone', familyInvitePlaceholder: 'Ex.: Mãe', familyRelation: 'Relação', relationFamily: 'Família', relationPartner: 'Parceiro', relationFriend: 'Amigo', addMember: 'Adicionar', sharingContent: 'O que compartilhar', shareItinerary: 'Plano diário', shareLocation: 'Localização ao vivo', shareBookings: 'Reservas e ingressos', shareAlerts: 'Alertas de segurança', shareUntil: 'Compartilhar até', untilTripEnd: 'Fim da viagem', until24Hours: 'Próximas 24 horas', untilManual: 'Desativar manualmente', sendCheckIn: 'Estou bem', copyInvite: 'Copiar convite', startFamilySharing: 'Ativar compartilhamento', updateFamilySharing: 'Salvar configurações', stopFamilySharing: 'Pausar tudo', familyMemberMother: 'Mãe', familyMemberBrother: 'Irmão', familyBadgeOn: 'Compartilhando', familyBadgeOff: 'Desativado', familySummaryOff: 'Compartilhamento desativado', familySummaryActive: 'Compartilhamento familiar ativo', memberJoined: 'Participando', memberInvited: 'Convite enviado', removeMember: 'Remover membro', familyNoMembers: 'Adicione pelo menos um familiar', familyMemberCount: '{count} membros', familyPlanShared: 'Plano compartilhado com {count} familiares'
    }
  };

  Object.entries(familyLocalePacks).forEach(([locale, pack]) => Object.assign(translations[locale], pack));

  const familyChatLocalePacks = {
    ja: { familyChat: '家族チャット', navFamily: '家族', familySpace: 'ファミリースペース', familyChatTitle: '家族チャット', familyChatSubtitle: '同じ家族に参加して、会話や旅程の共有、安否確認ができます。', registerAccount: 'アカウント作成', loginAccount: 'ログイン', createOrJoinFamily: '家族を作成または参加', createFamily: '家族を作成', joinFamily: '招待コードで参加', shareCurrentTrip: '現在の旅程をチャットに共有', sendMessage: '送信', familyChatLoginHint: 'ログインして家族チャットへ', copyInviteCode: '招待コードをコピー', leaveFamily: '家族から退出' },
    ko: { familyChat: '가족 채팅', navFamily: '가족', familySpace: '가족 공간', familyChatTitle: '가족 채팅', familyChatSubtitle: '같은 가족에 들어와 대화하고 일정과 안부를 공유하세요.', registerAccount: '계정 만들기', loginAccount: '로그인', createOrJoinFamily: '가족 만들기 또는 참여', createFamily: '가족 만들기', joinFamily: '초대 코드로 참여', shareCurrentTrip: '현재 일정을 채팅에 공유', sendMessage: '보내기', familyChatLoginHint: '로그인 후 가족 채팅 이용', copyInviteCode: '초대 코드 복사', leaveFamily: '가족 나가기' },
    fr: { familyChat: 'Discussion familiale', navFamily: 'Famille', familySpace: 'Espace famille', familyChatTitle: 'Discussion familiale', familyChatSubtitle: 'Rejoignez la même famille pour discuter, partager le voyage et rassurer vos proches.', registerAccount: 'Créer un compte', loginAccount: 'Se connecter', createOrJoinFamily: 'Créer ou rejoindre une famille', createFamily: 'Créer une famille', joinFamily: 'Rejoindre avec un code', shareCurrentTrip: 'Partager le voyage dans le chat', sendMessage: 'Envoyer', familyChatLoginHint: 'Connectez-vous au chat familial', copyInviteCode: 'Copier le code', leaveFamily: 'Quitter la famille' },
    es: { familyChat: 'Chat familiar', navFamily: 'Familia', familySpace: 'Espacio familiar', familyChatTitle: 'Chat familiar', familyChatSubtitle: 'Entren en la misma familia para hablar, compartir el viaje y avisar que están bien.', registerAccount: 'Crear cuenta', loginAccount: 'Iniciar sesión', createOrJoinFamily: 'Crear o unirse a una familia', createFamily: 'Crear familia', joinFamily: 'Unirse con código', shareCurrentTrip: 'Compartir el viaje en el chat', sendMessage: 'Enviar', familyChatLoginHint: 'Inicia sesión en el chat familiar', copyInviteCode: 'Copiar código', leaveFamily: 'Salir de la familia' },
    de: { familyChat: 'Familienchat', navFamily: 'Familie', familySpace: 'Familienbereich', familyChatTitle: 'Familienchat', familyChatSubtitle: 'Gemeinsam chatten, Reisepläne teilen und sicher Bescheid geben.', registerAccount: 'Konto erstellen', loginAccount: 'Anmelden', createOrJoinFamily: 'Familie erstellen oder beitreten', createFamily: 'Familie erstellen', joinFamily: 'Mit Code beitreten', shareCurrentTrip: 'Aktuelle Reise im Chat teilen', sendMessage: 'Senden', familyChatLoginHint: 'Für den Familienchat anmelden', copyInviteCode: 'Code kopieren', leaveFamily: 'Familie verlassen' },
    it: { familyChat: 'Chat di famiglia', navFamily: 'Famiglia', familySpace: 'Spazio famiglia', familyChatTitle: 'Chat di famiglia', familyChatSubtitle: 'Entrate nella stessa famiglia per parlare, condividere il viaggio e rassicurare tutti.', registerAccount: 'Crea account', loginAccount: 'Accedi', createOrJoinFamily: 'Crea o unisciti a una famiglia', createFamily: 'Crea famiglia', joinFamily: 'Entra con codice', shareCurrentTrip: 'Condividi il viaggio nella chat', sendMessage: 'Invia', familyChatLoginHint: 'Accedi alla chat di famiglia', copyInviteCode: 'Copia codice', leaveFamily: 'Lascia famiglia' },
    th: { familyChat: 'แชตครอบครัว', navFamily: 'ครอบครัว', familySpace: 'พื้นที่ครอบครัว', familyChatTitle: 'แชตครอบครัว', familyChatSubtitle: 'เข้าครอบครัวเดียวกันเพื่อคุย แชร์แผนเที่ยว และแจ้งความปลอดภัย', registerAccount: 'สร้างบัญชี', loginAccount: 'เข้าสู่ระบบ', createOrJoinFamily: 'สร้างหรือเข้าร่วมครอบครัว', createFamily: 'สร้างครอบครัว', joinFamily: 'เข้าร่วมด้วยรหัส', shareCurrentTrip: 'แชร์ทริปในแชต', sendMessage: 'ส่ง', familyChatLoginHint: 'เข้าสู่ระบบเพื่อเข้าแชต', copyInviteCode: 'คัดลอกรหัส', leaveFamily: 'ออกจากครอบครัว' },
    ar: { familyChat: 'دردشة العائلة', navFamily: 'العائلة', familySpace: 'مساحة العائلة', familyChatTitle: 'دردشة العائلة', familyChatSubtitle: 'انضموا إلى العائلة نفسها للدردشة ومشاركة الرحلة والاطمئنان.', registerAccount: 'إنشاء حساب', loginAccount: 'تسجيل الدخول', createOrJoinFamily: 'إنشاء عائلة أو الانضمام', createFamily: 'إنشاء عائلة', joinFamily: 'الانضمام برمز', shareCurrentTrip: 'مشاركة الرحلة في الدردشة', sendMessage: 'إرسال', familyChatLoginHint: 'سجّل الدخول إلى دردشة العائلة', copyInviteCode: 'نسخ الرمز', leaveFamily: 'مغادرة العائلة' },
    ru: { familyChat: 'Семейный чат', navFamily: 'Семья', familySpace: 'Семейное пространство', familyChatTitle: 'Семейный чат', familyChatSubtitle: 'Общайтесь, делитесь маршрутом и сообщайте близким, что всё хорошо.', registerAccount: 'Создать аккаунт', loginAccount: 'Войти', createOrJoinFamily: 'Создать семью или вступить', createFamily: 'Создать семью', joinFamily: 'Вступить по коду', shareCurrentTrip: 'Отправить поездку в чат', sendMessage: 'Отправить', familyChatLoginHint: 'Войдите в семейный чат', copyInviteCode: 'Копировать код', leaveFamily: 'Выйти из семьи' },
    'pt-BR': { familyChat: 'Chat da família', navFamily: 'Família', familySpace: 'Espaço da família', familyChatTitle: 'Chat da família', familyChatSubtitle: 'Entrem na mesma família para conversar, compartilhar a viagem e avisar que estão bem.', registerAccount: 'Criar conta', loginAccount: 'Entrar', createOrJoinFamily: 'Criar ou entrar em uma família', createFamily: 'Criar família', joinFamily: 'Entrar com código', shareCurrentTrip: 'Compartilhar viagem no chat', sendMessage: 'Enviar', familyChatLoginHint: 'Entre no chat da família', copyInviteCode: 'Copiar código', leaveFamily: 'Sair da família' }
  };

  Object.entries(familyChatLocalePacks).forEach(([locale, pack]) => Object.assign(translations[locale], pack));

  let currentLocale = 'zh-CN';

  function normalizeLocale(locale) {
    if (supported.some(item => item.code === locale)) return locale;
    const base = String(locale || '').toLowerCase().split('-')[0];
    const match = supported.find(item => item.code.toLowerCase().split('-')[0] === base);
    return match ? match.code : 'zh-CN';
  }

  function t(key, variables = {}) {
    const pack = translations[currentLocale] || en;
    const template = pack[key] || en[key] || key;
    return String(template).replace(/\{(\w+)\}/g, (_, name) => variables[name] ?? `{${name}}`);
  }

  function localeInfo(code = currentLocale) {
    return supported.find(item => item.code === code) || supported[0];
  }

  function apply(root = document) {
    root.querySelectorAll('[data-i18n]').forEach(element => {
      element.textContent = t(element.dataset.i18n);
    });
    root.querySelectorAll('[data-i18n-aria]').forEach(element => {
      element.setAttribute('aria-label', t(element.dataset.i18nAria));
    });
    const info = localeInfo();
    document.documentElement.lang = info.code;
    document.documentElement.dir = info.dir;
    const code = document.getElementById('currentLanguageCode');
    if (code) code.textContent = info.short;
    const drawerName = document.getElementById('drawerLanguageName');
    if (drawerName) drawerName.textContent = info.native;
    document.title = `${t('appName')} · EasyTrip`;
  }

  function setLocale(locale, options = {}) {
    const next = normalizeLocale(locale);
    currentLocale = next;
    if (options.persist !== false) {
      try { localStorage.setItem('easytrip-locale', next); } catch (error) { /* Storage may be unavailable. */ }
    }
    apply();
    document.dispatchEvent(new CustomEvent('easytrip:localechange', { detail: { locale: next, info: localeInfo(next), announce: options.announce !== false } }));
  }

  function init() {
    let saved = '';
    try { saved = localStorage.getItem('easytrip-locale') || ''; } catch (error) { /* Storage may be unavailable. */ }
    currentLocale = normalizeLocale(saved || navigator.language || 'zh-CN');
    apply();
    return currentLocale;
  }

  function formatDate(date, options) {
    try { return new Intl.DateTimeFormat(currentLocale, options).format(date); }
    catch (error) { return new Intl.DateTimeFormat('en', options).format(date); }
  }

  window.EasyTripI18n = {
    supported,
    translations,
    t,
    init,
    apply,
    setLocale,
    formatDate,
    localeInfo,
    get locale() { return currentLocale; }
  };
})();
